# .peavers.yml - Addon metadata for peavers.io website

# Icon to display on website
iconType: BestInSlotRuneIcon

# CurseForge project ID for download statistics
curseForgeProjectId: 1459083

# Tags for filtering and categorization
tags:
  - gear
  - best-in-slot
